name: CI CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # First job compile
  Compile:
    runs-on: custom   # Shared runner
    steps:
      - uses: actions/checkout@v4     # Checkout files

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn compile

  # Second job Security-check
  Security-check:
    runs-on: custom    # Shared runner
    needs: Compile

    steps:
      - uses: actions/checkout@v4     # Checkout files

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      # Download all project dependencies before scanning.
      # This populates the local Maven cache (~/.m2) so Trivy doesn't
      # repeatedly download dependencies from Maven Central.
      - name: Download dependencies
        run: mvn dependency:go-offline

      # Trivy FS Scan is a filesystem security scan used before building a Docker image in a CI/CD pipeline.
      # It scans the project directory for dependency vulnerabilities (CVEs), exposed secrets,
      # Infrastructure-as-Code misconfigurations, and optionally license issues.
      # Trivy FS Scan checks -> Dependency Vulnerabilities, Secrets, IaC Misconfigurations, License Issues
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # This command scans your local file system for security risks and saves the results as a JSON file.
      - name: Run Trivy FS Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: json
          output: fs-report.json

      # Clean temporary files from previous runs.
      # Required for self-hosted runners because the Gitleaks action
      # downloads files to /tmp, which persists across workflow runs.
      - name: Clean old Gitleaks temp files
        run: rm -rf /tmp/gitleaks*

      # A Static Application Security Testing (SAST) tool to automatically detect
      # and prevent hardcoded secrets—such as API keys, passwords, cloud tokens,
      # and database credentials—from being exposed in source code.
      #
      # The official Gitleaks GitHub Action installs and runs Gitleaks automatically,
      # so no separate installation or CLI command is required.
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

  # Job Three: Testing maven
  Test:
    runs-on: custom    # Shared runner
    needs: Security-check

    steps:
      - uses: actions/checkout@v4     # Checkout files

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      # Download all project dependencies before scanning.
      # This populates the local Maven cache (~/.m2) so Trivy doesn't
      # repeatedly download dependencies from Maven Central.
      - name: Test Maven
        run: mvn test

  # Job Four: Installing SonarQube and Scanning
  sonarqube:
    runs-on: custom
    needs: Test
    steps:
    - uses: actions/checkout@v6
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Package JAR
      run: mvn package -DskipTests  
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
          name: app-jar
          path: target/*.jar 
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v8.2.1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}     

  
    # Check the Quality Gate status.
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      with:
        pollingTimeoutSec: 600
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }} #OPTIONAL

# Job Five: Downloding artifacts 
  Download_artifact:
    runs-on: self-hosted
    needs: sonarqube
    steps:
    - uses: actions/checkout@v4
    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: app-jar
        path: app  # this will download JAR to ./app folder
  
  # Job Six: Docker download 
  Docker:
    runs-on: custom
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v4
      with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        push: true
        tags: ravikudal/app:latest